### ISSUE TITLE
No block given

### ISSUE THREAD

**Issue by jaymzh** [lamont-cookbooks/multipackage#6]
The more you use this the longer the install can take, so I treid to add a timeout.... but I get:

```
LocalJumpError
--------------
no block given (yield)
```

and it points to this line:

```
 64:    multipackage list_of_packages do
 65:      action :upgrade
 66>>     timeout 480
 67:    end
```

:(

**Comment by jaymzh** [comment]
It seems like it's something magic about `timeout` the name. If I change it to `timeout2`, then I get no such error...

**Comment by lamont-granquist** [comment]
Yep something definitely 'magic' about `#timeout`:

```
% cat /home/lamont/.chef/local-mode-cache/cache/chef-stacktrace.out
Generated at 2015-10-28 13:36:45 -0700
LocalJumpError: no block given (yield)
/opt/chefdk/embedded/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
/opt/chefdk/embedded/lib/ruby/2.1.0/timeout.rb:35:in `block in catch'
/opt/chefdk/embedded/lib/ruby/2.1.0/timeout.rb:35:in `catch'
/opt/chefdk/embedded/lib/ruby/2.1.0/timeout.rb:35:in `catch'
/opt/chefdk/embedded/lib/ruby/2.1.0/timeout.rb:106:in `timeout'
/opt/chefdk/embedded/lib/ruby/2.1.0/timeout.rb:127:in `timeout'
/home/lamont/.chef/local-mode-cache/cache/cookbooks/test/recipes/default.rb:4:in `block in from_file'
/home/lamont/.chefdk/gem/ruby/2.1.0/gems/chef-12.5.1/lib/chef/dsl/definitions.rb:35:in `instance_eval'
/home/lamont/.chefdk/gem/ruby/2.1.0/gems/chef-12.5.1/lib/chef/dsl/definitions.rb:35:in `evaluate_resource_definition'
/home/lamont/.chefdk/gem/ruby/2.1.0/gems/chef-12.5.1/lib/chef/dsl/definitions.rb:14:in `multipackage'
/home/lamont/.chef/local-mode-cache/cache/cookbooks/test/recipes/default.rb:3:in `from_file'
/home/lamont/.chefdk/gem/ruby/2.1.0/gems/chef-12.5.1/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/home/lamont/.chefdk/gem/ruby/2.1.0/gems/chef-12.5.1/lib/chef/mixin/from_file.rb:30:in `from_file'
/home/lamont/.chefdk/gem/ruby/2.1.0/gems/chef-12.5.1/lib/chef/cookbook_version.rb:228:in `load_recipe'
/home/lamont/.chefdk/gem/ruby/2.1.0/gems/chef-12.5.1/lib/chef/run_context.rb:293:in `load_recipe'
/home/lamont/.chefdk/gem/ruby/2.1.0/gems/chef-12.5.1/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
/home/lamont/.chefdk/gem/ruby/2.1.0/gems/chef-12.5.1/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
/home/lamont/.chefdk/gem/ruby/2.1.0/gems/chef-12.5.1/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
/home/lamont/.chefdk/gem/ruby/2.1.0/gems/chef-12.5.1/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
/home/lamont/.chefdk/gem/ruby/2.1.0/gems/chef-12.5.1/lib/chef/run_context.rb:158:in `load'
/home/lamont/.chefdk/gem/ruby/2.1.0/gems/chef-12.5.1/lib/chef/policy_builder/expand_node_object.rb:91:in `setup_run_context'
/home/lamont/.chefdk/gem/ruby/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:490:in `setup_run_context'
/home/lamont/.chefdk/gem/ruby/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:268:in `run'
/home/lamont/.chefdk/gem/ruby/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:270:in `block in fork_chef_client'
/home/lamont/.chefdk/gem/ruby/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:258:in `fork'
/home/lamont/.chefdk/gem/ruby/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:258:in `fork_chef_client'
/home/lamont/.chefdk/gem/ruby/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:224:in `block in run_chef_client'
/home/lamont/.chefdk/gem/ruby/2.1.0/gems/chef-12.5.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/home/lamont/.chefdk/gem/ruby/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:212:in `run_chef_client'
/home/lamont/.chefdk/gem/ruby/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:414:in `block in interval_run_chef_client'
/home/lamont/.chefdk/gem/ruby/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:404:in `loop'
/home/lamont/.chefdk/gem/ruby/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:404:in `interval_run_chef_client'
/home/lamont/.chefdk/gem/ruby/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:394:in `run_application'
/home/lamont/.chefdk/gem/ruby/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:60:in `run'
/home/lamont/.chefdk/gem/ruby/2.1.0/gems/chef-12.5.1/bin/chef-client:26:in `<top (required)>'
/opt/chefdk/bin/chef-client:54:in `load'
/opt/chefdk/bin/chef-client:54:in `<main>'%                                                     
```

**Comment by lamont-granquist** [comment]
![Double Facepalm](http://fakeplus.com/pictures/jpg/-double-facepalm_20120514083424.jpg)

**Comment by lamont-granquist** [comment]
Commenting this out in ruby itself makes it run fine:

https://github.com/ruby/ruby/blob/832c74f428db6c5bd6e575e1f6ea7fe0891c84d2/lib/timeout.rb#L115-L118

**Comment by lamont-granquist** [comment]
And definitions use method_missing to populate the params hash, because of course it has to be method_missing's fault somewhere in here:

https://github.com/chef/chef/blob/8d32fdd4377476a9f7dc36a864ccdaa17c32b3a1/lib/chef/resource_definition.rb#L57-L62

Since require 'timeout' pulls that bogus method directly into the binding that required it, the result is that we've got a timeout method, and so method_missing doesn't fire because the method ain't missing.   Resources don't get trolled by this because properties are real methods on an object which override the bogus timeout method and don't rely on method_missing magic.

Now I understand what the problem is, I'm not sure exactly what to do about it.  I'm leaning towards converting the definition to a method that just does shit properly...
